<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Tempest.Core\Tempest.Core.csproj" />
    <ProjectReference Include="..\..\Tempest.Workspace\Tempest.Workspace.csproj" />
  </ItemGroup>

</Project>
