using Tempest.Core.Modules;

namespace TempestSampleModule;

/// <summary>
/// Replace this summary with a description of what this module does.
/// </summary>
/// <remarks>
/// Generated by the TempestOS module template (<c>dotnet new tempest-module</c>).
/// See <c>docs/academy/02 Runtime Architecture/03-building-a-module.md</c>
/// ("Building a Module") for the full guide this template follows, and
/// this project's own <c>README.md</c> for next steps.
/// </remarks>
[ModuleMetadata("TEMPEST_MODULE_ID", "TEMPEST_MODULE_DISPLAY_NAME", "TEMPEST_MODULE_VERSION")]
public sealed class TempestSampleModule : ModuleLifecycleBase
{
    public TempestSampleModule()
        : base("TEMPEST_MODULE_ID", "TEMPEST_MODULE_DISPLAY_NAME", "TEMPEST_MODULE_VERSION")
    {
    }

    // Every lifecycle method below is virtual and defaults to a no-op -
    // override only the ones this module actually needs. For example:
    //
    // public override Task StartAsync(CancellationToken cancellationToken)
    // {
    //     // ... this module's own startup logic ...
    //     return Task.CompletedTask;
    // }
    //
    // [ModuleMetadataAttribute] above already lets this constructor
    // request a DI-public platform service (ILogger, IEventBus, and so
    // on) directly - add the parameter and assign it to a field, exactly
    // as Tempest.Samples.ClockModule does. Without the attribute, this
    // constructor would need to stay parameterless (see "Building a
    // Module.md").
}
